"""empty message

Revision ID: 045b941a9a10
Revises: 9bb88b8afb24
Create Date: 2021-08-11 18:56:09.665628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045b941a9a10'
down_revision = '9bb88b8afb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('test', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'test')
    # ### end Alembic commands ###
