"""empty message

Revision ID: 0d9bba725705
Revises: 57cbc378469c
Create Date: 2021-12-21 15:59:55.799765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9bba725705'
down_revision = '57cbc378469c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.drop_column('student', 'password')
    op.drop_column('student', 'graduation_year')
    op.drop_column('student', 'first_name')
    op.drop_column('student', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('student', 'full_name')
    # ### end Alembic commands ###
