"""empty message

Revision ID: 0f03940ba6e1
Revises: afa440fcc202
Create Date: 2021-12-21 19:03:29.435928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f03940ba6e1'
down_revision = 'afa440fcc202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password')
    # ### end Alembic commands ###
