"""empty message

Revision ID: 2f335b0ad1f3
Revises: a6712c38981e
Create Date: 2021-12-09 21:27:23.040294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f335b0ad1f3'
down_revision = 'a6712c38981e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('hours', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
