"""empty message

Revision ID: 57cbc378469c
Revises: 2f335b0ad1f3
Create Date: 2021-12-09 21:27:36.197061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cbc378469c'
down_revision = '2f335b0ad1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'hours')
    # ### end Alembic commands ###
