"""empty message

Revision ID: 7ce601e4d203
Revises: 045b941a9a10
Create Date: 2021-08-11 19:08:19.689796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce601e4d203'
down_revision = '045b941a9a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'date')
    # ### end Alembic commands ###
