"""empty message

Revision ID: a3701f0692df
Revises: 0f03940ba6e1
Create Date: 2021-12-21 19:06:41.159349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3701f0692df'
down_revision = '0f03940ba6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('google_id', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'google_id')
    # ### end Alembic commands ###
