"""empty message

Revision ID: a6712c38981e
Revises: ebf8d5aa7d26
Create Date: 2021-12-09 20:53:23.972764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6712c38981e'
down_revision = 'ebf8d5aa7d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'is_verified')
    # ### end Alembic commands ###
