"""empty message

Revision ID: ae84d9e263a8
Revises: a3701f0692df
Create Date: 2021-12-21 20:49:34.979754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae84d9e263a8'
down_revision = 'a3701f0692df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('supervisor_notes', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'supervisor_notes')
    # ### end Alembic commands ###
