"""empty message

Revision ID: afa440fcc202
Revises: 0d9bba725705
Create Date: 2021-12-21 19:01:57.369659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa440fcc202'
down_revision = '0d9bba725705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id2', sa.String(length=150), nullable=False))
    op.add_column('student', sa.Column('password', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password')
    op.drop_column('student', 'id2')
    # ### end Alembic commands ###
