"""empty message

Revision ID: ebf8d5aa7d26
Revises: 7ce601e4d203
Create Date: 2021-08-11 22:04:52.978996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf8d5aa7d26'
down_revision = '7ce601e4d203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_activity_key', 'record', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('record_activity_key', 'record', ['activity'])
    # ### end Alembic commands ###
